# Pre-commit configuration for secret leak protection
# Copy this file to individual repos as .pre-commit-config.yaml

default_install_hook_types: [pre-commit, prepare-commit-msg]
default_stages: [pre-commit]

repos:
  # Gitleaks - Secret detection
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        name: gitleaks-scan
        description: Detect hardcoded secrets using Gitleaks
        entry: gitleaks detect --no-git --verbose --redact
        language: golang
        stages: [pre-commit]
        pass_filenames: false

  # Add verification to commit message
  - repo: local
    hooks:
      - id: gitleaks-verified
        name: Add Gitleaks verification to commit
        description: Add verification that gitleaks scan passed to commit message
        entry: bash -c 'echo "" >> "$1"; echo "✅ Gitleaks scan passed - no secrets detected" >> "$1"'
        language: system
        stages: [prepare-commit-msg]
        pass_filenames: false
        always_run: true
