# Pre-commit configuration for secret leak protection
# Copy this file to individual repos as .pre-commit-config.yaml

default_install_hook_types: [pre-commit, prepare-commit-msg]
default_stages: [pre-commit]

repos:
  # Gitleaks - Secret detection
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        name: gitleaks-scan
        description: Detect hardcoded secrets using Gitleaks
        entry: gitleaks detect --no-git --verbose --redact
        language: golang
        stages: [pre-commit]
        pass_filenames: false

  # Add commit trailer with verification
  - repo: local
    hooks:
      - id: gitleaks-verified
        name: Gitleaks Verification Complete
        description: Add security verification trailer to commit
        entry: git interpret-trailers --trailer "Pre-commit:✅ enabled" --in-place
        language: system
        stages: [prepare-commit-msg]
        pass_filenames: true
        always_run: true
